/**
 * Drizzle schema — Den.
 *
 * Migration 001 (Stage 1): the auth/identity layer from BACKBONE §5.
 *   users · auth_identities · webauthn_credentials · invite_codes · sessions ·
 *   push_subscriptions
 *
 * Migration 002 (Stage 2): chat core from BACKBONE §5.
 *   friendships · chats · chat_members · messages
 *
 * Migration 003 (Stage 3): media from BACKBONE §5/§7.
 *   media
 *
 * Migration 004 (Stage 5): tags from BACKBONE §5.
 *   tags · media_tags
 *
 * Migration 005 (post-MVP): replies + reactions.
 *   messages.reply_to_message_id (self-FK) · message_reactions
 *
 * Migration 006 (post-MVP, docs/MESSAGE_SEARCH.md): message search.
 *   pg_trgm extension + gin trigram index on messages.body (substring
 *   search, not tsvector FTS — see the plan doc for why).
 *
 * Migration 007 (post-MVP, docs/MESSAGE_EDIT.md): message edit.
 *   messages.edited_at (nullable timestamptz) — set on first edit; no index
 *   needed (idx_messages_body_trgm already covers search over edited bodies).
 *
 * Migration 008 (post-MVP, docs/VOICE_WAVEFORM.md): voice waveforms.
 *   media.waveform (nullable jsonb) — 44 RMS peaks (0–255) computed at
 *   processing time; voice only, null for image/video and legacy rows.
 *
 * Migration 009 (post-MVP, docs/RECEIPTS.md): delivered watermark.
 *   chat_members.last_delivered_message_id (nullable bigint, no FK, mirrors
 *   last_read_message_id) — advanced by a client delivery ack; both watermarks
 *   are guarded-monotonic writes (never move backwards).
 *
 * Migration 010 (post-MVP, docs/EMBEDS.md §4): embed framework + Instagram.
 *   embeds — belongs to a message exactly as media does; messages_kind_check
 *   gains 'embed'.
 *
 * ⚠️ auth_identities and webauthn_credentials ship NOW but MVP writes NOTHING to
 * them (OAuth = post-MVP #2, passkeys = post-MVP #1). They exist so those land
 * as an INSERT pattern, not a migration. Do not implement OAuth/passkeys yet.
 */
import { sql } from 'drizzle-orm';
import {
  bigint,
  boolean,
  check,
  customType,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  type AnyPgColumn,
} from 'drizzle-orm/pg-core';

/** Case-insensitive text. Requires `CREATE EXTENSION citext` (in migration 001). */
const citext = customType<{ data: string }>({
  dataType() {
    return 'citext';
  },
});

/** COSE public key blob for passkeys (post-MVP; column exists from 001). */
const bytea = customType<{ data: Buffer; default: false }>({
  dataType() {
    return 'bytea';
  },
});

// ─── users & auth ───────────────────────────────────────────────────────────

export const users = pgTable('users', {
  id: bigint('id', { mode: 'bigint' }).generatedAlwaysAsIdentity().primaryKey(),
  username: citext('username').notNull().unique(),
  displayName: text('display_name').notNull(),
  email: citext('email').unique(), // nullable in MVP; OAuth account-linking key later
  passwordHash: text('password_hash'), // argon2id; NULLABLE — OAuth-only accounts have none
  avatarKey: text('avatar_key'), // R2 key, nullable
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const authIdentities = pgTable(
  'auth_identities',
  {
    id: bigint('id', { mode: 'bigint' }).generatedAlwaysAsIdentity().primaryKey(),
    userId: bigint('user_id', { mode: 'bigint' })
      .notNull()
      .references(() => users.id),
    provider: text('provider').notNull(), // 'google' | 'github' | ...
    providerUserId: text('provider_user_id').notNull(), // STABLE id (Google 'sub'). ⚠️ never key on email
    emailAtLink: citext('email_at_link'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('auth_identities_provider_uid').on(t.provider, t.providerUserId)],
);

export const webauthnCredentials = pgTable('webauthn_credentials', {
  id: text('id').primaryKey(), // credential ID (base64url) from authenticator
  userId: bigint('user_id', { mode: 'bigint' })
    .notNull()
    .references(() => users.id),
  publicKey: bytea('public_key').notNull(), // COSE public key
  signCount: bigint('sign_count', { mode: 'bigint' }).notNull().default(sql`0`),
  transports: text('transports').array(), // ['internal','hybrid',...]
  deviceLabel: text('device_label'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
});

export const inviteCodes = pgTable('invite_codes', {
  code: text('code').primaryKey(), // random, generated by admin CLI
  createdBy: bigint('created_by', { mode: 'bigint' }).references(() => users.id), // nullable: first invite has no creator
  usedBy: bigint('used_by', { mode: 'bigint' }).references(() => users.id),
  usedAt: timestamp('used_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const sessions = pgTable(
  'sessions',
  {
    id: text('id').primaryKey(), // random 256-bit token, cookie value
    userId: bigint('user_id', { mode: 'bigint' })
      .notNull()
      .references(() => users.id),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    userAgent: text('user_agent'),
  },
  (t) => [index('sessions_user').on(t.userId)],
);

export const pushSubscriptions = pgTable(
  'push_subscriptions',
  {
    id: bigint('id', { mode: 'bigint' }).generatedAlwaysAsIdentity().primaryKey(),
    userId: bigint('user_id', { mode: 'bigint' })
      .notNull()
      .references(() => users.id),
    endpoint: text('endpoint').notNull().unique(),
    p256dh: text('p256dh').notNull(),
    auth: text('auth').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('push_subscriptions_user').on(t.userId)],
);

// ─── friendships & chats (Stage 2) ──────────────────────────────────────────

export const friendships = pgTable(
  'friendships',
  {
    userA: bigint('user_a', { mode: 'bigint' })
      .notNull()
      .references(() => users.id),
    userB: bigint('user_b', { mode: 'bigint' })
      .notNull()
      .references(() => users.id),
    status: text('status').notNull(), // 'pending' | 'accepted'
    requestedBy: bigint('requested_by', { mode: 'bigint' })
      .notNull()
      .references(() => users.id),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    acceptedAt: timestamp('accepted_at', { withTimezone: true }),
  },
  (t) => [
    primaryKey({ columns: [t.userA, t.userB] }),
    check('friendships_status_check', sql`${t.status} IN ('pending','accepted')`),
    check('friendships_order_check', sql`${t.userA} < ${t.userB}`),
  ],
);

export const chats = pgTable('chats', {
  id: bigint('id', { mode: 'bigint' }).generatedAlwaysAsIdentity().primaryKey(),
  isGroup: boolean('is_group').notNull(),
  name: text('name'), // null for DMs (derive from other member)
  avatarKey: text('avatar_key'),
  // "minId:maxId" for DMs, null for groups — enforces one DM chat per pair (§5).
  dmKey: text('dm_key').unique(),
  createdBy: bigint('created_by', { mode: 'bigint' })
    .notNull()
    .references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const chatMembers = pgTable(
  'chat_members',
  {
    chatId: bigint('chat_id', { mode: 'bigint' })
      .notNull()
      .references(() => chats.id),
    userId: bigint('user_id', { mode: 'bigint' })
      .notNull()
      .references(() => users.id),
    role: text('role').notNull().default('member'),
    joinedAt: timestamp('joined_at', { withTimezone: true }).notNull().defaultNow(),
    lastReadMessageId: bigint('last_read_message_id', { mode: 'bigint' }), // unread counts
    // Migration 009 (post-MVP, docs/RECEIPTS.md): true device-delivery
    // watermark, distinct from lastReadMessageId — advanced by a client ack
    // when a message actually reaches this device (not just "server has it").
    lastDeliveredMessageId: bigint('last_delivered_message_id', { mode: 'bigint' }),
  },
  (t) => [
    primaryKey({ columns: [t.chatId, t.userId] }),
    check('chat_members_role_check', sql`${t.role} IN ('owner','member')`),
    index('chat_members_user').on(t.userId),
  ],
);

// ─── messages (Stage 2 text; media kinds land Stage 3) ──────────────────────

export const messages = pgTable(
  'messages',
  {
    id: bigint('id', { mode: 'bigint' }).generatedAlwaysAsIdentity().primaryKey(),
    chatId: bigint('chat_id', { mode: 'bigint' })
      .notNull()
      .references(() => chats.id),
    senderId: bigint('sender_id', { mode: 'bigint' })
      .notNull()
      .references(() => users.id),
    kind: text('kind').notNull(), // 'text' | 'image' | 'video' | 'voice' | 'system'
    body: text('body'), // text content or caption
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    // Post-MVP (migration 005): self-referencing FK for message replies.
    // Nullable — most messages aren't replies. No ON DELETE behavior specified;
    // soft-deletes mean the referenced row is never actually removed (§5/CLAUDE.md #8).
    replyToMessageId: bigint('reply_to_message_id', { mode: 'bigint' }).references(
      (): AnyPgColumn => messages.id,
    ),
    // Post-MVP (migration 007, docs/MESSAGE_EDIT.md): set the first time the
    // message's body is edited; null if never edited. No time limit on edits.
    editedAt: timestamp('edited_at', { withTimezone: true }),
  },
  (t) => [
    check(
      'messages_kind_check',
      // 'embed' added migration 010 (docs/EMBEDS.md §4.1).
      sql`${t.kind} IN ('text','image','video','voice','embed','system')`,
    ),
    index('idx_messages_chat').on(t.chatId, t.id.desc()),
    // Substring search over body (text + captions), not word/stemmer-based
    // FTS — pg_trgm handles mixed-language/partial-word matches the way
    // Discord-style search is expected to (docs/MESSAGE_SEARCH.md §3.1).
    // Requires `CREATE EXTENSION pg_trgm` (hand-added to the generated
    // migration, same convention as citext in migration 001 — see
    // CITEXT_EXTENSION below).
    index('idx_messages_body_trgm').using('gin', t.body.op('gin_trgm_ops')),
  ],
);

// ─── media (Stage 3) ─────────────────────────────────────────────────────

export const media = pgTable(
  'media',
  {
    id: bigint('id', { mode: 'bigint' }).generatedAlwaysAsIdentity().primaryKey(),
    messageId: bigint('message_id', { mode: 'bigint' })
      .notNull()
      .references(() => messages.id),
    uploaderId: bigint('uploader_id', { mode: 'bigint' })
      .notNull()
      .references(() => users.id),
    kind: text('kind').notNull(), // 'image' | 'video' | 'voice'
    r2Key: text('r2_key').notNull(),
    mime: text('mime').notNull(),
    sizeBytes: bigint('size_bytes', { mode: 'bigint' }).notNull(),
    width: bigint('width', { mode: 'number' }), // images/videos
    height: bigint('height', { mode: 'number' }),
    durationMs: bigint('duration_ms', { mode: 'number' }), // videos/voice
    waveform: jsonb('waveform').$type<number[]>(), // voice only: 44 RMS peaks 0–255 (docs/VOICE_WAVEFORM.md)
    thumbKey: text('thumb_key'), // R2 key of thumbnail (null for voice)
    status: text('status').notNull().default('processing'), // 'processing' | 'ready' | 'failed'
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    check('media_kind_check', sql`${t.kind} IN ('image','video','voice')`),
    check('media_status_check', sql`${t.status} IN ('processing','ready','failed')`),
    index('idx_media_message').on(t.messageId),
  ],
);

// ─── embeds (post-MVP, docs/EMBEDS.md §4.1) ──────────────────────────────

export const embeds = pgTable(
  'embeds',
  {
    id: bigint('id', { mode: 'bigint' }).generatedAlwaysAsIdentity().primaryKey(),
    messageId: bigint('message_id', { mode: 'bigint' })
      .notNull()
      .references(() => messages.id),
    provider: text('provider').notNull(), // 'instagram' | 'vault'
    status: text('status').notNull().default('processing'), // 'processing' | 'ready' | 'failed'
    // Normalized card snapshot (provider-agnostic — the shared client
    // renderer, EmbedCard.tsx, reads only these, never provider internals).
    title: text('title'),
    subtitle: text('subtitle'), // author handle / doc owner
    description: text('description'), // caption / summary
    thumbKey: text('thumb_key'), // R2 key of the snapshot image (nullable)
    canonicalUrl: text('canonical_url'), // external URL (deep-link target)
    providerRef: text('provider_ref'), // IG shortcode | vault documentId
    contentKind: text('content_kind'), // 'video' | 'image' | 'document'
    actionType: text('action_type').notNull().default('external'), // 'external' | 'read' | 'portal'
    data: jsonb('data').$type<Record<string, unknown>>(), // provider extras (og:video url, etc.)
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    check('embeds_provider_check', sql`${t.provider} IN ('instagram','vault')`),
    check('embeds_status_check', sql`${t.status} IN ('processing','ready','failed')`),
    check('embeds_action_type_check', sql`${t.actionType} IN ('external','read','portal')`),
    index('idx_embeds_message').on(t.messageId),
  ],
);

// ─── tags (Stage 5) ──────────────────────────────────────────────────────

export const tags = pgTable(
  'tags',
  {
    id: bigint('id', { mode: 'bigint' }).generatedAlwaysAsIdentity().primaryKey(),
    chatId: bigint('chat_id', { mode: 'bigint' })
      .notNull()
      .references(() => chats.id),
    name: citext('name').notNull(), // normalized (§5): lowercase, spaces→hyphens
    usageCount: integer('usage_count').notNull().default(0),
    createdBy: bigint('created_by', { mode: 'bigint' })
      .notNull()
      .references(() => users.id),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('tags_chat_id_name_unique').on(t.chatId, t.name)],
);

export const mediaTags = pgTable(
  'media_tags',
  {
    mediaId: bigint('media_id', { mode: 'bigint' })
      .notNull()
      .references(() => media.id),
    tagId: bigint('tag_id', { mode: 'bigint' })
      .notNull()
      .references(() => tags.id),
    taggedBy: bigint('tagged_by', { mode: 'bigint' }) // attribution only, not ownership (§5)
      .notNull()
      .references(() => users.id),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.mediaId, t.tagId] }),
    index('idx_media_tags_tag').on(t.tagId, t.mediaId), // the gallery-query index (§5)
  ],
);

// ─── message reactions (post-MVP, migration 005) ────────────────────────

export const messageReactions = pgTable(
  'message_reactions',
  {
    messageId: bigint('message_id', { mode: 'bigint' })
      .notNull()
      .references(() => messages.id),
    userId: bigint('user_id', { mode: 'bigint' })
      .notNull()
      .references(() => users.id),
    emoji: text('emoji').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.messageId, t.userId, t.emoji] }),
    index('idx_message_reactions_message').on(t.messageId), // aggregation query
  ],
);

/** Raw SQL run before the tables in migration 001 (citext type must exist). */
export const CITEXT_EXTENSION = sql`CREATE EXTENSION IF NOT EXISTS citext`;

/** Raw SQL hand-added to migration 006 (pg_trgm's gin index needs the
 *  extension present first) — see idx_messages_body_trgm above. Standard
 *  Postgres contrib module; present in the postgres:16-alpine compose image
 *  and any normal VPS Postgres install. */
export const PG_TRGM_EXTENSION = sql`CREATE EXTENSION IF NOT EXISTS pg_trgm`;
