/**
 * Drizzle schema — Den.
 *
 * Migration 001 (Stage 1): the auth/identity layer from BACKBONE §5.
 *   users · auth_identities · webauthn_credentials · invite_codes · sessions ·
 *   push_subscriptions
 *
 * Migration 002 (Stage 2): chat core from BACKBONE §5.
 *   friendships · chats · chat_members · messages
 *
 * The media/tag tables (media, tags, media_tags) are Stage 3/5 and land in
 * later migrations — not here, per "stages ship in order" (CLAUDE.md).
 *
 * ⚠️ auth_identities and webauthn_credentials ship NOW but MVP writes NOTHING to
 * them (OAuth = post-MVP #2, passkeys = post-MVP #1). They exist so those land
 * as an INSERT pattern, not a migration. Do not implement OAuth/passkeys yet.
 */
import { sql } from 'drizzle-orm';
import {
  bigint,
  boolean,
  check,
  customType,
  index,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core';

/** Case-insensitive text. Requires `CREATE EXTENSION citext` (in migration 001). */
const citext = customType<{ data: string }>({
  dataType() {
    return 'citext';
  },
});

/** COSE public key blob for passkeys (post-MVP; column exists from 001). */
const bytea = customType<{ data: Buffer; default: false }>({
  dataType() {
    return 'bytea';
  },
});

// ─── users & auth ───────────────────────────────────────────────────────────

export const users = pgTable('users', {
  id: bigint('id', { mode: 'bigint' }).generatedAlwaysAsIdentity().primaryKey(),
  username: citext('username').notNull().unique(),
  displayName: text('display_name').notNull(),
  email: citext('email').unique(), // nullable in MVP; OAuth account-linking key later
  passwordHash: text('password_hash'), // argon2id; NULLABLE — OAuth-only accounts have none
  avatarKey: text('avatar_key'), // R2 key, nullable
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const authIdentities = pgTable(
  'auth_identities',
  {
    id: bigint('id', { mode: 'bigint' }).generatedAlwaysAsIdentity().primaryKey(),
    userId: bigint('user_id', { mode: 'bigint' })
      .notNull()
      .references(() => users.id),
    provider: text('provider').notNull(), // 'google' | 'github' | ...
    providerUserId: text('provider_user_id').notNull(), // STABLE id (Google 'sub'). ⚠️ never key on email
    emailAtLink: citext('email_at_link'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex('auth_identities_provider_uid').on(t.provider, t.providerUserId)],
);

export const webauthnCredentials = pgTable('webauthn_credentials', {
  id: text('id').primaryKey(), // credential ID (base64url) from authenticator
  userId: bigint('user_id', { mode: 'bigint' })
    .notNull()
    .references(() => users.id),
  publicKey: bytea('public_key').notNull(), // COSE public key
  signCount: bigint('sign_count', { mode: 'bigint' }).notNull().default(sql`0`),
  transports: text('transports').array(), // ['internal','hybrid',...]
  deviceLabel: text('device_label'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
});

export const inviteCodes = pgTable('invite_codes', {
  code: text('code').primaryKey(), // random, generated by admin CLI
  createdBy: bigint('created_by', { mode: 'bigint' }).references(() => users.id), // nullable: first invite has no creator
  usedBy: bigint('used_by', { mode: 'bigint' }).references(() => users.id),
  usedAt: timestamp('used_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const sessions = pgTable(
  'sessions',
  {
    id: text('id').primaryKey(), // random 256-bit token, cookie value
    userId: bigint('user_id', { mode: 'bigint' })
      .notNull()
      .references(() => users.id),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    userAgent: text('user_agent'),
  },
  (t) => [index('sessions_user').on(t.userId)],
);

export const pushSubscriptions = pgTable(
  'push_subscriptions',
  {
    id: bigint('id', { mode: 'bigint' }).generatedAlwaysAsIdentity().primaryKey(),
    userId: bigint('user_id', { mode: 'bigint' })
      .notNull()
      .references(() => users.id),
    endpoint: text('endpoint').notNull().unique(),
    p256dh: text('p256dh').notNull(),
    auth: text('auth').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('push_subscriptions_user').on(t.userId)],
);

// ─── friendships & chats (Stage 2) ──────────────────────────────────────────

export const friendships = pgTable(
  'friendships',
  {
    userA: bigint('user_a', { mode: 'bigint' })
      .notNull()
      .references(() => users.id),
    userB: bigint('user_b', { mode: 'bigint' })
      .notNull()
      .references(() => users.id),
    status: text('status').notNull(), // 'pending' | 'accepted'
    requestedBy: bigint('requested_by', { mode: 'bigint' })
      .notNull()
      .references(() => users.id),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    acceptedAt: timestamp('accepted_at', { withTimezone: true }),
  },
  (t) => [
    primaryKey({ columns: [t.userA, t.userB] }),
    check('friendships_status_check', sql`${t.status} IN ('pending','accepted')`),
    check('friendships_order_check', sql`${t.userA} < ${t.userB}`),
  ],
);

export const chats = pgTable('chats', {
  id: bigint('id', { mode: 'bigint' }).generatedAlwaysAsIdentity().primaryKey(),
  isGroup: boolean('is_group').notNull(),
  name: text('name'), // null for DMs (derive from other member)
  avatarKey: text('avatar_key'),
  // "minId:maxId" for DMs, null for groups — enforces one DM chat per pair (§5).
  dmKey: text('dm_key').unique(),
  createdBy: bigint('created_by', { mode: 'bigint' })
    .notNull()
    .references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const chatMembers = pgTable(
  'chat_members',
  {
    chatId: bigint('chat_id', { mode: 'bigint' })
      .notNull()
      .references(() => chats.id),
    userId: bigint('user_id', { mode: 'bigint' })
      .notNull()
      .references(() => users.id),
    role: text('role').notNull().default('member'),
    joinedAt: timestamp('joined_at', { withTimezone: true }).notNull().defaultNow(),
    lastReadMessageId: bigint('last_read_message_id', { mode: 'bigint' }), // unread counts
  },
  (t) => [
    primaryKey({ columns: [t.chatId, t.userId] }),
    check('chat_members_role_check', sql`${t.role} IN ('owner','member')`),
    index('chat_members_user').on(t.userId),
  ],
);

// ─── messages (Stage 2 text; media kinds land Stage 3) ──────────────────────

export const messages = pgTable(
  'messages',
  {
    id: bigint('id', { mode: 'bigint' }).generatedAlwaysAsIdentity().primaryKey(),
    chatId: bigint('chat_id', { mode: 'bigint' })
      .notNull()
      .references(() => chats.id),
    senderId: bigint('sender_id', { mode: 'bigint' })
      .notNull()
      .references(() => users.id),
    kind: text('kind').notNull(), // 'text' | 'image' | 'video' | 'voice' | 'system'
    body: text('body'), // text content or caption
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (t) => [
    check(
      'messages_kind_check',
      sql`${t.kind} IN ('text','image','video','voice','system')`,
    ),
    index('idx_messages_chat').on(t.chatId, t.id.desc()),
  ],
);

/** Raw SQL run before the tables in migration 001 (citext type must exist). */
export const CITEXT_EXTENSION = sql`CREATE EXTENSION IF NOT EXISTS citext`;
