/**
 * Video transcode checks (docs/VIDEO_TRANSCODE.md §5).
 *
 * Fixtures are **generated by ffmpeg at run time** rather than committed — a
 * repo full of binary test videos ages badly, and synthesizing them means the
 * inputs are described by the code that uses them.
 *
 * This calls `processMedia` directly rather than driving an upload, because
 * the questions here are about what comes out of the pipeline (codec, mime,
 * orientation, which key survives), not about the HTTP path — which
 * scripts/probe-passkey.ts-style end-to-end coverage already exercises
 * elsewhere.
 *
 * ⚠️ Dev stack only: it writes real objects to R2/MinIO under a throwaway
 * chat id and deletes them afterwards.
 */
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomBytes } from 'node:crypto';
import { probeCodecs, probeMedia, runFfmpeg } from '../media/ffmpeg.js';
import { processMedia } from '../media/process.js';
import { deleteObject, getObjectBuffer, putObjectBuffer } from '../media/r2.js';
import { closeDb } from '../db/index.js';

let failures = 0;
function check(label: string, ok: boolean, detail = ''): void {
  console.log(`  ${ok ? 'PASS' : 'FAIL'}  ${label}${detail ? `  — ${detail}` : ''}`);
  if (!ok) failures++;
}

/** A synthetic clip. `extra` lets a case pick codecs/orientation. */
async function makeFixture(
  dir: string,
  name: string,
  opts: { width: number; height: number; seconds: number; vcodec: string; audio: boolean; container: string },
): Promise<string> {
  const path = join(dir, `${name}.${opts.container}`);
  const args = [
    '-y',
    '-f', 'lavfi', '-i', `testsrc=size=${opts.width}x${opts.height}:rate=15:duration=${opts.seconds}`,
  ];
  if (opts.audio) {
    args.push('-f', 'lavfi', '-i', `sine=frequency=440:duration=${opts.seconds}`);
  }
  args.push('-c:v', opts.vcodec, '-pix_fmt', 'yuv420p');
  if (opts.vcodec === 'libx265') args.push('-tag:v', 'hvc1');
  args.push(...(opts.audio ? ['-c:a', 'aac'] : ['-an']));
  args.push('-t', String(opts.seconds), path);
  await runFfmpeg(args, 60_000);
  return path;
}

const rnd = (): string => randomBytes(4).toString('hex');

async function runCase(
  label: string,
  dir: string,
  fixture: { width: number; height: number; seconds: number; vcodec: string; audio: boolean; container: string },
  assertions: (r: {
    result: Awaited<ReturnType<typeof processMedia>>;
    outCodecs: Awaited<ReturnType<typeof probeCodecs>>;
    outProbe: Awaited<ReturnType<typeof probeMedia>>;
    originalGone: boolean;
    tmp: string;
  }) => void,
): Promise<void> {
  console.log(`\n${label}`);
  const chatId = 999_000n + BigInt(Math.floor(Math.random() * 1000));
  const mediaId = BigInt(Date.now() % 1_000_000) + BigInt(Math.floor(Math.random() * 1000));
  const originalKey = `probe/${rnd()}/original`;

  const path = await makeFixture(dir, `fx-${rnd()}`, fixture);
  const { readFile } = await import('node:fs/promises');
  await putObjectBuffer(originalKey, await readFile(path), 'application/octet-stream');

  const result = await processMedia({ chatId, mediaId, kind: 'video', originalKey });

  // Pull whatever the pipeline says it stored, and inspect it for real.
  const stored = await getObjectBuffer(result.r2Key);
  const tmp = join(dir, `out-${rnd()}.bin`);
  const { writeFile } = await import('node:fs/promises');
  await writeFile(tmp, stored);

  const outCodecs = await probeCodecs(tmp);
  const outProbe = await probeMedia(tmp);

  let originalGone = false;
  if (result.r2Key !== originalKey) {
    try {
      await getObjectBuffer(originalKey);
    } catch {
      originalGone = true;
    }
  }

  assertions({ result, outCodecs, outProbe, originalGone, tmp });

  // Tidy up whatever survived.
  for (const key of [result.r2Key, result.thumbKey, originalKey]) {
    if (key) await deleteObject(key).catch(() => {});
  }
}

async function main(): Promise<void> {
  const dir = await mkdtemp(join(tmpdir(), 'den-probe-video-'));
  console.log('\nVideo transcode probe (fixtures generated by ffmpeg)\n');

  try {
    // ── 1. the iPhone case: HEVC in a .mov ───────────────────────────────
    // This is the bug the whole feature exists for. Before, this row was
    // stored as-is and labelled video/mp4 — undecodable on most Android and
    // desktop Chrome, and announced as something it wasn't.
    await runCase(
      '1. HEVC/.mov (the iPhone case) is re-encoded to H.264/AAC',
      dir,
      { width: 640, height: 360, seconds: 2, vcodec: 'libx265', audio: true, container: 'mov' },
      ({ result, outCodecs, originalGone }) => {
        check('output video codec is h264', outCodecs.videoCodec === 'h264', String(outCodecs.videoCodec));
        check('output audio codec is aac', outCodecs.audioCodec === 'aac', String(outCodecs.audioCodec));
        check('mime says video/mp4 and is now true', result.mime === 'video/mp4', result.mime);
        check('a NEW key was stored (not the original)', result.r2Key.endsWith('video.mp4'), result.r2Key);
        check('the original was deleted', originalGone);
        check('a poster frame was produced', Boolean(result.thumbKey));
        check('duration survived', (result.durationMs ?? 0) > 1000, `${result.durationMs}ms`);
      },
    );

    // ── 2. already H.264/AAC → the cheap path ────────────────────────────
    await runCase(
      '2. an already-H.264/AAC mp4 takes the remux path',
      dir,
      { width: 640, height: 360, seconds: 2, vcodec: 'libx264', audio: true, container: 'mp4' },
      ({ result, outCodecs }) => {
        check('still h264', outCodecs.videoCodec === 'h264', String(outCodecs.videoCodec));
        check('still aac', outCodecs.audioCodec === 'aac', String(outCodecs.audioCodec));
        check('mime is video/mp4', result.mime === 'video/mp4', result.mime);
        check('stored under the derived key', result.r2Key.endsWith('video.mp4'), result.r2Key);
      },
    );

    // ── 3. no audio track ────────────────────────────────────────────────
    // `-c:a aac` against a file with no audio is a classic way to make ffmpeg
    // fail; the code branches to `-an` instead.
    await runCase(
      '3. a silent video survives (no audio stream)',
      dir,
      { width: 480, height: 270, seconds: 2, vcodec: 'libx265', audio: false, container: 'mov' },
      ({ result, outCodecs }) => {
        check('video transcoded to h264', outCodecs.videoCodec === 'h264', String(outCodecs.videoCodec));
        check('no audio stream invented', outCodecs.audioCodec === null, String(outCodecs.audioCodec));
        check('mime is video/mp4', result.mime === 'video/mp4', result.mime);
      },
    );

    // ── 4. portrait orientation ──────────────────────────────────────────
    // The scale filter caps the LONG edge; a naive `min(1920,iw)`/`min(1080,ih)`
    // would squash portrait video into a landscape box.
    await runCase(
      '4. a portrait video stays portrait',
      dir,
      { width: 360, height: 640, seconds: 2, vcodec: 'libx265', audio: true, container: 'mov' },
      ({ result, outProbe }) => {
        check(
          'output is taller than it is wide',
          (outProbe.height ?? 0) > (outProbe.width ?? 0),
          `${outProbe.width}x${outProbe.height}`,
        );
        check(
          'recorded dimensions match the stored file',
          result.width === outProbe.width && result.height === outProbe.height,
          `row ${result.width}x${result.height} vs file ${outProbe.width}x${outProbe.height}`,
        );
      },
    );

    // ── 5. oversized input is capped ─────────────────────────────────────
    await runCase(
      '5. a 4K input is capped at 1920 on the long edge',
      dir,
      { width: 3840, height: 2160, seconds: 1, vcodec: 'libx264', audio: false, container: 'mp4' },
      ({ result, outProbe }) => {
        // ⚠️ This input is ALREADY h264 — the case most likely to slip through
        // an over-eager "already the right codec, just remux it" check. The
        // cap has to beat the codec check, or every 4K phone video sails past.
        const longEdge = Math.max(outProbe.width ?? 0, outProbe.height ?? 0);
        check('long edge was capped to 1920', longEdge === 1920, `${outProbe.width}x${outProbe.height}`);
        check(
          'the row records what was actually stored',
          result.width === outProbe.width && result.height === outProbe.height,
          `row ${result.width}x${result.height} vs file ${outProbe.width}x${outProbe.height}`,
        );
      },
    );

    console.log(`\n${failures === 0 ? '✓ all checks passed' : `✗ ${failures} check(s) failed`}\n`);
    if (failures > 0) process.exitCode = 1;
  } finally {
    await rm(dir, { recursive: true, force: true });
    await closeDb();
  }
}

void main();
